### ISSUE TITLE
Duplicate error handling

### ISSUE THREAD

**Issue by aclowkey** [globocom/echo-prometheus#5]
Enabling the middleware causes the error handling function to be called twice, thus producing duplicate response.
```go
package main

import (
	"errors"
	"net/http"

	"github.com/labstack/echo-contrib/prometheus"

	"github.com/labstack/echo/v4"
)

func main() {
	// Echo instance
	e := echo.New()
	p := prometheus.NewPrometheus("api", nil)
	p.Use(e)

	// Routes
	e.GET("/", func(context echo.Context) error {
		return errors.New("Bad error")
	})

	// Error handling
	e.HTTPErrorHandler = func(err error, context echo.Context) {
		type CustomErr struct {
			Action string
		}
		_ = context.JSON(http.StatusBadRequest, CustomErr{"dummy"})
	}

	// Start server
	e.Logger.Fatal(e.Start(":1323"))
}

```

Produces the customErr twice.
```sh 
curl localhost:1323/ | jq                                                
{
  "Action": "dummy"
}
{
  "Action": "dummy"
}
```

**Comment by aclowkey** [comment]
The error handling is called twice:

1. 
https://github.com/globocom/echo-prometheus/blob/c88a211575260adef1a5ec52ea8fa858ec597a6e/middleware.go#L111
Then the error is returned to echo.Handler, which also calls the error handling function in 
2. 
https://github.com/labstack/echo/blob/8dd25c39ced4fafbe63e361c281f2275d7d9fa41/echo.go#L619

**Comment by aclowkey** [comment]
Looks like it's handled here
https://github.com/labstack/echo-contrib/issues/36

**Comment by wpjunior** [comment]
Hello @aclowkey you could avoid this behavior checking the Commited variable, like this:

```
package main

import (
	"errors"
	"net/http"

	echoPrometheus "github.com/globocom/echo-prometheus"
	"github.com/labstack/echo/v4"
)

func main() {
	// Echo instance
	e := echo.New()
	e.Use(echoPrometheus.MetricsMiddleware())

	// Routes
	e.GET("/", func(context echo.Context) error {
		return errors.New("Bad error")
	})

	// Error handling
	e.HTTPErrorHandler = func(err error, context echo.Context) {
		if context.Response().Committed {
			return
		}
		type CustomErr struct {
			Action string
		}
		_ = context.JSON(http.StatusBadRequest, CustomErr{"dummy"})
	}

	// Start server
	e.Logger.Fatal(e.Start(":1323"))
}

```

**Comment by wpjunior** [comment]
@aclowkey when you inspect the default error handler of echo framework, you note that it have this condition check: https://github.com/labstack/echo/blob/master/echo.go#L371

**Comment by aclowkey** [comment]
Thanks for the workaround!
Is the check necessary as far as this handler goes?

**Comment by corpix** [comment]
For those who come here from google because of similar behavior with your own middlewares
Here https://github.com/globocom/echo-prometheus/blob/9ae975523cfc327f82381486a4af3b381e4bfe5e/middleware.go#L112 you can see `c.Error(...)` call. This will directly invoke `e.HTTPErrorHandler`. so: don't use `c.Error(...)` in middlewares if you want to be compatible with `e.HTTPErrorHandler` customization
